# Generated by Django 5.0.6 on 2024-07-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='describe',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
